# Generated by Django 5.0.6 on 2024-06-13 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='total_worked_hours',
            new_name='total_days_worked',
        ),
    ]
